/**
 * Periodic prune of the on-disk Next.js caches.
 *
 * These directories have no eviction of any kind — Next never caps them. On this
 * shared Hostinger plan that is the binding constraint: inodes sit at ~70% of the
 * 3M ceiling and a sibling app reached 4GB in .next/cache/images alone.
 *
 * Two things the older version of this prune got wrong, both fixed here:
 *
 *   1. It waited 5 minutes before the first run. Apps on this plan are
 *      OOM-recycled roughly hourly and were measured respawning twice inside two
 *      minutes; every restart destroys the pending timer. A prune that only runs
 *      on a process surviving five unbroken minutes never actually runs. Now 45s.
 *
 *   2. Age alone is not a bound. With `minimumCacheTTL` at 30 days and image
 *      variants per breakpoint, a 14-day sweep can still leave GBs standing.
 *      There is now a hard SIZE cap that evicts oldest-first.
 *
 * Everything deleted is transparently regenerated by Next on the next request, so
 * this can never break a page — the cost is one slower re-optimization. CPU on
 * this plan runs at 4-12%, so trading CPU for disk and inodes is the right way round.
 *
 * NOTE: node builtins are loaded via `process.getBuiltinModule` (Node 20.16+/22),
 * NOT `await import("node:fs/promises")`. Instrumentation is compiled for the Edge
 * runtime as well, where a `node:` specifier either fails the Turbopack bundle or
 * throws UnhandledSchemeError under webpack. A runtime call is invisible to both
 * bundlers, and the NEXT_RUNTIME guard already guarantees this only runs on Node.
 */

function envMb(name: string, fallbackMb: number): number {
  const raw = Number(process.env[name]);
  const mb = Number.isFinite(raw) && raw > 0 ? raw : fallbackMb;
  return mb * 1024 * 1024;
}

const PRUNE_TARGETS = [
  { dir: ".next/cache/images", maxAgeDays: 14, maxBytes: envMb("NEXT_IMAGE_CACHE_MAX_MB", 512) },
  { dir: ".next/cache/fetch-cache", maxAgeDays: 14, maxBytes: envMb("NEXT_FETCH_CACHE_MAX_MB", 256) },
];

const FIRST_RUN_DELAY_MS = 45 * 1000;
const RUN_EVERY_MS = 6 * 60 * 60 * 1000;

const g = globalThis as unknown as { __cachePruneArmed?: boolean };

/** Arm the prune. Idempotent across dev hot-reloads and repeat register() calls. */
export function startCachePrune(): void {
  if (g.__cachePruneArmed) return;
  if (process.env.NEXT_PHASE === "phase-production-build") return;
  g.__cachePruneArmed = true;
  // unref() so the timers never hold the process open on shutdown.
  const first = setTimeout(() => {
    void prune();
    setInterval(() => void prune(), RUN_EVERY_MS).unref?.();
  }, FIRST_RUN_DELAY_MS);
  first.unref?.();
}

/** Run one sweep now. Exported for tests. */
export async function prune(): Promise<void> {
  try {
    // process.getBuiltinModule needs Node >= 20.16 / 22.3. If the host runs older
    // Node this would be `undefined` and the TypeError would be swallowed by the
    // catch below — a prune that silently does nothing is precisely how this
    // plan reached 4GB and 70% inodes twice already. Fail LOUDLY instead.
    if (typeof process.getBuiltinModule !== "function") {
      console.error(
        "[cache-prune] DISABLED: process.getBuiltinModule is unavailable — this host needs Node >= 20.16 / 22.3. " +
          ".next/cache will grow without any bound until this is fixed.",
      );
      return;
    }
    const fs = process.getBuiltinModule("node:fs/promises");
    const path = process.getBuiltinModule("node:path");

    for (const target of PRUNE_TARGETS) {
      const cutoff = Date.now() - target.maxAgeDays * 24 * 60 * 60 * 1000;
      const files: { p: string; mtimeMs: number; size: number }[] = [];
      const dirs: string[] = [];

      async function walk(dir: string): Promise<void> {
        let entries;
        try {
          entries = await fs.readdir(dir, { withFileTypes: true });
        } catch {
          return; // dir gone or unreadable — nothing to prune
        }
        for (const entry of entries) {
          const p = path.join(dir, entry.name);
          try {
            if (entry.isDirectory()) {
              await walk(p);
              dirs.push(p);
            } else {
              const st = await fs.stat(p);
              files.push({ p, mtimeMs: st.mtimeMs, size: st.size });
            }
          } catch {
            // an entry disappearing mid-walk is fine — skip it
          }
        }
      }
      await walk(path.join(process.cwd(), target.dir));
      if (files.length === 0) continue;

      let removed = 0;
      let freed = 0;
      const survivors: typeof files = [];

      // Pass 1 — age.
      for (const f of files) {
        if (f.mtimeMs < cutoff) {
          if (await fs.unlink(f.p).then(() => true, () => false)) {
            removed++;
            freed += f.size;
          }
        } else {
          survivors.push(f);
        }
      }

      // Pass 2 — hard size cap, oldest first. This is the actual guarantee.
      let total = survivors.reduce((n, f) => n + f.size, 0);
      if (total > target.maxBytes) {
        survivors.sort((a, b) => a.mtimeMs - b.mtimeMs);
        for (const f of survivors) {
          if (total <= target.maxBytes) break;
          if (await fs.unlink(f.p).then(() => true, () => false)) {
            total -= f.size;
            removed++;
            freed += f.size;
          }
        }
      }

      // Deepest-first so a directory emptied by its children can also go.
      for (const d of dirs.reverse()) {
        try {
          if ((await fs.readdir(d)).length === 0) await fs.rmdir(d);
        } catch {
          /* not empty or already gone */
        }
      }

      if (removed > 0) {
        console.log(
          `[cache-prune] ${target.dir}: removed ${removed} files (${(freed / 1048576).toFixed(0)}MB), ` +
            `${(total / 1048576).toFixed(0)}MB remaining, cap ${(target.maxBytes / 1048576).toFixed(0)}MB`,
        );
      }
    }
  } catch (err) {
    console.error("[cache-prune] failed:", err instanceof Error ? err.message : err);
  }
}
